### ISSUE TITLE
Inline/zero-copy processing broken

### ISSUE THREAD

**Issue by falkTX** [guysherman/jack-passthrough#1]
Currently you have the following processing code:

```
    in = (jack_default_audio_sample_t *)jack_port_get_buffer(it->first, nframes);
    out = (jack_default_audio_sample_t *)jack_port_get_buffer(it->second, nframes);
    memcpy(out, in, sizeof(jack_default_audio_sample_t) * nframes);
```

This assumes that in != out, but that is not always the case.
Under some conditions the audio buffer pointer can be the same (aka inline processing or zero-copy).
Please check if the pointer doesn't match, and only copy memory in that case.

Thanks.

**Comment by guysherman** [comment]
Fixed in: https://github.com/guysherman/jack-passthrough/commit/aad03b7c5ccc4a4dcb8fa38c49aa64cb9d628660
